# Generated by Django 5.2.8 on 2025-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_roomtype_room_room_type_hotel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'number')},
        ),
    ]
