# Generated by Django 5.2.8 on 2025-12-23 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Номер телефона должен быть цифровым')], verbose_name='Phone Number'),
        ),
    ]
